Repository alexliesenfeld/health, pull requests merged in 2022-10, with the labels that each got.

#56 add a go.sum
  examples/go.sum
  go.sum
Labels: hacktoberfest, hacktoberfest-accepted

#60 Feat memcache check
  checks/docker-compose.yaml
  checks/memcache/go.mod
  checks/memcache/go.sum
  checks/memcache/memcache.go
  checks/memcache/memcache_test.go
Labels: hacktoberfest

#58 add mongo check
  checks/docker-compose.yaml
  checks/mongo/go.mod
  checks/mongo/go.sum
  checks/mongo/mongo.go
  checks/mongo/mongo_test.go
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
